### ISSUE TITLE
colab 常用命令

### ISSUE THREAD

**Issue by aiastia** [aiastia/note#71]
挂载谷歌云盘 
````
from google.colab import drive
drive.mount('/content/drive')
````

**Comment by aiastia** [comment]
显示文件个数
````
%cd /content/drive/Shareddrives/
!ls -l | grep "^-" | wc -l
!ls -lR| grep "^-" | wc -l
````

**Comment by aiastia** [comment]
移动前100个文件到文件B
````
%cd /content/drive/Shareddrives/小说1/文学读物/中篇9112部
!mkdir /content/drive/Shareddrives/小说1/2
!ls -Q /content/drive/Shareddrives/小说1 | head -800 | xargs -i mv "/content/drive/Shareddrives/小说1/{}" /content/drive/Shareddrives/小说2/8/
````

**Comment by aiastia** [comment]
!url=1 ;echo 1+$url

**Comment by aiastia** [comment]
txt 合并到一个文件带 文件名

````
````

**Comment by aiastia** [comment]
[1.txt](https://github.com/aiastia/note/files/9378592/1.txt)

**Comment by aiastia** [comment]
[Linux下的文件批量转换为UTF8编码-enca](https://www.cnblogs.com/cxt-janson/p/10769009.html)
一、简介
enca是Linux下的文件编码转换工具。
二、源码包

http://dl.cihar.com/enca/
 
三、使用方法

````
enca -L zh_CN file 检查文件的编码 
enca -L zh_CN -x UTF-8 file 将文件编码转换为"UTF-8"编码 
enca -L zh_CN -x utf-8 *  把文件夹下的所有文件转换为utf8编码
 ````

四、批量转换

````
find -type f | xargs enca -L zh_CN -x UTF-8
````

**Comment by aiastia** [comment]
find -type f .txt | xargs enca -L zh_CN -x UTF-8 "{}"

**Comment by aiastia** [comment]
````
a=0
b="152本萝莉小说"
g="GB"
u="UTF" 
cd $b
for i in *.txt
 do
 echo $i ;
 a=$(($a + 1));
 echo "第$a 本书:" >> ../$b.txt;
 #echo $i >> 1.txt ;
 echo ${i%*${i:(-4)}} >> ../$b.txt ;
 #cat  "$i" | iconv -f GBK -t UTF-8 >> ../$b.txt
 f=`enca -L zh_CN "$i" | cut -d ';' -f 2 `
 echo $f+1 ;
 if [[ $f == *$g* ]]; then h="GB18030" ;elif [[ $f == *$u* ]]; then h="UTF-8" ;else h="UTF-16";fi
 #if [[ $f = "GB*" ]]; then h="GBK" ;elif [[ $f = "UTF*" ]]; then h="UTF-8" ;else h="UTF-16" ;fi
 echo $h ;
 cat  "$i" | iconv -f $h -t UTF-8 >> ../$b.txt
 #enca -L zh_CN "$i" | cut -d ';' -f 2 |xargs -i cat  "$i" | iconv -f {} -t UTF-8 
 echo  " " >> ../$b.txt
done
````

**Comment by aiastia** [comment]
for i in ./*/*.txt

**Comment by aiastia** [comment]
a=0
find -type f -name "*.txt" -print0 | while read -d $'\0' fn; do
    echo "$fn"
	a=$(($a + 1));
    echo "第$a 本书:"
    echo ${i%*${i:(-4)}}

done

**Comment by aiastia** [comment]
````
a=0
b="123"
g="GB"
u="UTF" 
cd $b
find -type f -name "*.txt" -print0 | while read -d $'\0' i; do
    echo "$i"
	  a=$(($a + 1));
    echo "第$a 本书:"
    echo ${i%*${i:(-4)}}
    echo $i ;
    a=$(($a + 1));
    echo "第$a 本书:" >> ../$b.txt;
    #echo $i >> 1.txt ;
    echo ${i%*${i:(-4)}} >> ../$b.txt ;
    #cat  "$i" | iconv -f GBK -t UTF-8 >> ../$b.txt
    f=`enca -L zh_CN "$i" | cut -d ';' -f 2 `
    echo $f+1 ;
    if [[ $f == *$g* ]]; then h="GB18030" ;elif [[ $f == *$u* ]]; then h="UTF-8" ;else h="UTF-16";fi
    #if [[ $f = "GB*" ]]; then h="GBK" ;elif [[ $f = "UTF*" ]]; then h="UTF-8" ;else h="UTF-16" ;fi
    echo $h ;
    cat  "$i" | iconv -f $h -t UTF-8 >> ../$b.txt
    #enca -L zh_CN "$i" | cut -d ';' -f 2 |xargs -i cat  "$i" | iconv -f {} -t UTF-8 
    echo  " " >> ../$b.txt
done
````

**Comment by aiastia** [comment]
文件切割

split -b 20m log.txt n

**Comment by aiastia** [comment]
ubuntu 修改 ip
````
# This is the network config written by 'subiquity'
network:
  ethernets:
    ens18:
      dhcp4: true
  version: 2
````

**Comment by aiastia** [comment]
````
# Let NetworkManager manage all devices on this system
network:
    ethernets:
        ens18:                    ## network card name
            dhcp4: false
            addresses:
              - 192.168.0.213/24   ## set static IP
            routes:
              - to: default
                via: 192.168.0.31  ## gateway
            nameservers:
              addresses: [8.8.8.8,8.8.4.4,192.168.0.31]
    version: 2
````

sudo netplan apply
