### ISSUE TITLE
github 环境变量

### ISSUE THREAD

**Issue by aiastia** [aiastia/note#84]
在 GitHub Actions 中，机密信息可以定义在不同的层级，例如仓库机密（Repository secrets）和环境机密（Environment secrets）。在工作流文件中调用这些机密的方式会有所不同。

1. **仓库机密（Repository secrets）**：
   你可以使用以下语法来访问仓库机密：
   ```yaml
   ${{ secrets.SECRET_NAME }}
   ```
   例如：
   ```yaml
   ${{ secrets.DOCKER_PASSWORD }}
   ```

2. **环境机密（Environment secrets）**：
   要使用环境机密，你需要在工作流文件中为作业（job）指定环境。一旦设置了环境，就可以与调用仓库机密的方式相同来访问环境机密。

   使用环境机密的示例：
   ```yaml
   jobs:
     deploy:
       runs-on: ubuntu-latest
       environment: production  # 指定环境
       steps:
         - name: 访问环境机密
           run: echo ${{ secrets.ENV_SECRET_NAME }}
   ```

   在这个例子中，`ENV_SECRET_NAME` 是在 `production` 环境中定义的机密。通过在作业中设置 `environment` 字段为 `production`，工作流将能够访问为该环境定义的机密。
