### ISSUE TITLE
AdGuardhome 

### ISSUE THREAD

**Issue by aiastia** [aiastia/note#86]
为什么aAdGuardhome配置中开启了“重定向53端口到adguardhome”，AdGuardhome无法获取客户端的真实IP，而只能显示为localhost？
#iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
#iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
#[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
#[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
这几行iptables规则会将所有进入路由器的UDP/TCP 53端口流量重定向到本地(localhost)的53端口。由于重定向是在本地进行的，所以AdGuardhome收到的所有流量的源IP地址都将被重定向为localhost，导致Adguardhome客户端IP均显示为localhost 127.0.0.1。将这些防火墙规则加“#”注释或直接删除，再重启防火墙即可。

https://www.right.com.cn/forum/thread-8282165-1-1.html

**Comment by aiastia** [comment]
```
http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:3000
  session_ttl: 0s
users:
  - name: admin
    password: $2y$10$c7uukZxkrHIN4QgKmLCFEeTYUt6EXW6NEgUmiw18qruW1bdFDeYuu
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: zh-cn
theme: auto
dns:
  bind_hosts:
    - 0.0.0.0
  port: 1745
  anonymize_client_ip: false
  ratelimit: 0
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 56
  ratelimit_whitelist: []
  refuse_any: false
  upstream_dns:
    - 223.5.5.5
  upstream_dns_file: ""
  bootstrap_dns:
    - 119.29.29.29
    - 223.5.5.5
  fallback_dns: []
  upstream_mode: load_balance
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: true
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
  serve_plain_dns: true
  hostsfile_enabled: true
  pending_requests:
    enabled: true
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
querylog:
  dir_path: ""
  ignored: []
  interval: 2160h
  size_memory: 1000
  enabled: true
  file_enabled: true
statistics:
  dir_path: ""
  ignored: []
  interval: 24h
  enabled: true
filters:
  - enabled: true
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1628750870
  - enabled: true
    url: https://anti-ad.net/easylist.txt
    name: 'CHN: anti-AD'
    id: 1628750871
whitelist_filters: []
user_rules:
  - '@@||taobao.com^$important'
  - '@@||jd.com^important'
  - '@@||flyme.cn^$important'
  - '@@||meizu.com^$important'
  - '@@||wl.jd.com^$important'
  - '@@||flydigi.com^'
  - '@@||pv.sohu.com^$important'
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: UTC
    ids: []
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    ecosia: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites: []
  safe_fs_patterns:
    - /usr/bin/AdGuardHome/data/userfilters/*
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 24
  blocked_response_ttl: 10
  filtering_enabled: true
  parental_enabled: false
  safebrowsing_enabled: false
  protection_enabled: true
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: false
    dhcp: true
    hosts: true
  persistent: []
log:
  enabled: true
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 29

```

**Comment by aiastia** [comment]
```
http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:3000
  session_ttl: 16h40m
users:
  - name: root
    password: $2y$10$YjaKJn4UihCSxtVYoJoPXuZlhxIbWrTC1ws57qYFrF27auL4zVPgm
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: zh-cn
theme: auto
dns:
  bind_hosts:
    - 0.0.0.0
  port: 5553
  anonymize_client_ip: false
  ratelimit: 0
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 56
  ratelimit_whitelist: []
  refuse_any: false
  upstream_dns:
    - 117.50.10.10
    - '# OneDNS'
    - '#119.29.29.29'
    - '# 腾讯公共DNS'
    - 8.8.8.8
    - 1.1.1.1
    - 208.67.222.222
    - '# OpenDNS'
    - https://doh-139e5817-openwrt.doh.pub/dns-query
    - https://np47hmxoek.cloudflare-gateway.com/dns-query
    - https://dns.google/dns-query
    - '[/netflix.com/]tcp://159.75.94.25:5353'
    - '[/nflxvideo.net/]tcp://159.75.94.25:5353'
    - '[/nflxso.net/]tcp://159.75.94.25:5353'
    - '[/amazonaws.com/]tcp://159.75.94.25:5353'
    - '[/fast.com/]tcp://159.75.94.25:5353'
    - '[/netflix/]tcp://159.75.94.25:5353'
    - '[/netflix.com/]tcp://159.75.94.25:5353'
    - '[/netflix.net/]tcp://159.75.94.25:5353'
    - '[/nflxso.net/]tcp://159.75.94.25:5353'
    - '[/nflxext.com/]tcp://159.75.94.25:5353'
    - '[/nflximg.com/]tcp://159.75.94.25:5353'
    - '[/nflximg.net/]tcp://159.75.94.25:5353'
    - '[/nflxvideo.net/]tcp://159.75.94.25:5353'
    - '[/netflixdnstest0.com/]tcp://159.75.94.25:5353'
    - '[/netflixdnstest1.com/]tcp://159.75.94.25:5353'
    - '[/netflixdnstest2.com/]tcp://159.75.94.25:5353'
    - '[/netflixdnstest3.com/]tcp://159.75.94.25:5353'
    - '[/netflixdnstest4.com/]tcp://159.75.94.25:5353'
    - '[/netflixdnstest5.com/]tcp://159.75.94.25:5353'
    - '[/netflixdnstest6.com/]tcp://159.75.94.25:5353'
    - '[/netflixdnstest7.com/]tcp://159.75.94.25:5353'
    - '[/netflixdnstest8.com/]tcp://159.75.94.25:5353'
    - '[/netflixdnstest9.com/]tcp://159.75.94.25:5353'
    - '[/raw.githubusercontent.com/]1.0.0.1'
  upstream_dns_file: ""
  bootstrap_dns:
    - 119.29.29.29
    - 223.5.5.5
  fallback_dns:
    - 120.196.165.24
    - 211.136.192.6
  upstream_mode: load_balance
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_enabled: true
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: true
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
  serve_plain_dns: true
  hostsfile_enabled: true
  pending_requests:
    enabled: true
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
querylog:
  dir_path: ""
  ignored: []
  interval: 2160h
  size_memory: 1000
  enabled: true
  file_enabled: true
statistics:
  dir_path: ""
  ignored: []
  interval: 24h
  enabled: true
filters:
  - enabled: true
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1628750870
  - enabled: true
    url: https://anti-ad.net/easylist.txt
    name: 'CHN: anti-AD'
    id: 1628750871
whitelist_filters: []
user_rules:
  - '@@||taobao.com^$important'
  - '@@||jd.com^important'
  - '@@||flyme.cn^$important'
  - '@@||meizu.com^$important'
  - '@@||wl.jd.com^$important'
  - '@@||flydigi.com^'
  - '@@||pv.sohu.com^$important'
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: UTC
    ids: []
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    ecosia: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites: []
  safe_fs_patterns:
    - /usr/bin/AdGuardHome/data/userfilters/*
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 24
  blocked_response_ttl: 10
  filtering_enabled: true
  parental_enabled: false
  safebrowsing_enabled: false
  protection_enabled: true
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: false
    dhcp: true
    hosts: true
  persistent: []
log:
  enabled: true
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 30

```
